name: GitHub Actions Demo
on:
  push:
#      tags:
#        - orange-v*
#        - blue-v*
#        - green-V*
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on   the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set env
        run: |
          echo ::set-env name=COLOR_TAGS::$(echo ${GITHUB_REF##*/})
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        id: setenv
#
## ref) https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          # list of Docker images to use as base name for tags
#          images: |
#            luckypenny79/flask-app
##            ghcr.io/username/app
#          # generate Docker tags based on the following events/attributes
#          tags: |
#            type=schedule
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#            type=semver,pattern={{major}}
#            type=sha

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: luckypenny79/flask-app:${GITHUB_REF##*/}